import type { Metadata } from "next";
import { Header, LoadingContent, Sidebar } from "@/ui/molecules";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Header />
      <div className="flex w-[100vw]">
        <Sidebar />
        <main className="w-[82vw] p-6">{children}</main>
        <LoadingContent />
      </div>
    </>
  );
}
